config/routes.rb
Rails.application.routes.draw do
  resources :deliveries
  root       'deliveries#new'
   

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  before_save :delivery_calculation
  validates :from, :where, :length, :width, :height, :common_weight, :common_volume, :distance, presence: true
  validates :length, :width, :height, :common_weight, :common_volume, :distance, numericality: {greater_than: 0}
 
  # add calculation of delivery
  def delivery_calculation
    self.calculation = 500 + (self.distance * (self.length + self.width + self.height + self.common_weight))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]
 

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
    
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
   
  end
  
  
  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)
    
    respond_to do |format|
      if @delivery.save
                
        format.html {redirect_to @delivery, notice: 'Delivery was successfully created.'}
        format.json { render :show, status: :updated, location: @delivery }
      else
        format.html { render :new }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_params
      params.require(:delivery).permit(:from, :where, :length, :width, :height, :common_volume, :common_weight, :distance, :calculation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/_form.html.erb
<%= form_for(@delivery, validate: true) do |f| %>
  <% if @delivery.errors.any? %>
    <div id="error_explanation">
      <h2>Форма содержит <%= Russian::pluralize(@delivery.errors.count, "ошибку", "ошибки", "ошибок") %></h2>

      <ul>
      <% @delivery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from%>
  </div>
  <div class="field">
    <%= f.label :where %><br>
    <%= f.text_field :where %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>&nbsp;м
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>&nbsp;м
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>&nbsp;м
  </div>
  <div class="field">
    <%= f.label :common_volume %><br>
    <%= f.text_field :common_volume %> м&sup3;
  </div>
  <div class="field">
    <%= f.label :common_weight %><br>
    <%= f.text_field :common_weight %>&nbsp;кг
  </div>
   <div class="field">
    <%= f.hidden_field :distance %>&nbsp;
  </div>
  <div class="actions">
    <%= f.submit "Произвести расчет" %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Редактировать</h1>

<%= render 'form' %>

<%= link_to 'Показать', @delivery %> |
<%= link_to 'Список', deliveries_path %>

app/views/deliveries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список</h1>

<table>
  <thead>
    <tr>
      <th>Откуда</th>
      <th>Куда</th>
      <th>Длина</th>
      <th>Ширина</th>
      <th>Высота</th>
      <th>Общий объем</th>
      <th>Общий вес</th>
      <th>Расстояние</th>
      <th>Стоимость</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.from %></td>
        <td><%= delivery.where %></td>
        <td><%= delivery.length %></td>
        <td><%= delivery.width %></td>
        <td><%= delivery.height %></td>
        <td><%= delivery.common_volume %></td>
        <td><%= delivery.common_weight %></td>
        <td><%= delivery.distance %></td>
        <td><%= delivery.calculation%></td>
        <td><%= link_to 'Показать', delivery %></td>
        <td><%= link_to 'Редактировать', edit_delivery_path(delivery) %></td>
        <td><%= link_to 'Удалить', delivery, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%=link_to 'Новая доставка', root_path%>

<p>Топ-3 города отправки по популярности: 
<%=Delivery.group("from").order('count(*) DESC').limit(3).pluck("from").join(', ')%>.
</p>

app/views/deliveries/new.html.erb
<h1>Новая доставка</h1>

<%= render 'form' %>

<%= link_to 'Список', deliveries_path %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Откуда:</strong>
  <%= @delivery.from %>
</p>

<p>
  <strong>Куда:</strong>
  <%= @delivery.where %>
</p>

<p>
  <strong>Длина:</strong>
  <%= @delivery.length %>
</p>

<p>
  <strong>Ширина:</strong>
  <%= @delivery.width %>
</p>

<p>
  <strong>Высота:</strong>
  <%= @delivery.height %>
</p>

<p>
  <strong>Общий вес:</strong>
  <%= @delivery.common_volume %>
</p>

<p>
  <strong>Общий объем:</strong>
  <%= @delivery.common_weight %>
</p>

<p>
  <strong>Расстояние:</strong>
  <%= @delivery.distance %>
</p>

<p>
  <strong>Стоимость:</strong>
  <%= @delivery.calculation %>
</p>

<%= link_to 'Редактировать', edit_delivery_path(@delivery) %> |
<%= link_to 'Список', deliveries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Расчет стоимости доставки</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>